project:
  type: website
  output-dir: "../../../static/algebra"
  render:
    - "*.qmd"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
    html-math-method: mathjax
    output-file: "livro.html"
  revealjs:
    transition: slide
    scrollable: false
    slide-number: false
    output-file: "slides.html"
    theme: [default, custom.scss]
    width: 1280
    height: 800
    margin: 0.1
    footer: "UNICAMP — Instituto de Computação"
    include-after-body: assets/logos.html
    title-slide-attributes:
      data-background-image: "../assets/UNICAMP.png, ../assets/IC.png"
      data-background-size: "140px, 140px"
      data-background-position: "5% 8%, 95% 8%"
    chalkboard: 
      boardmarker-width: 3
      chalk-width: 3