project:
  type: website
  output-dir: "../../static/"
  lib-dir: site_libs
  render:
    - "*.qmd"
    - "**/*.qmd"
    - "**/**/*.qmd"
  preview:
    watch-inputs: true

execute:
  freeze: auto # 'auto' compila apenas os arquivos .qmd que foram alterados

format:
  html:
    theme: cosmo
    toc: true
    toc-title: "Sumário"
    toc-expand: true
    smooth-scroll: true
    fig-responsive: true    # Habilita CSS responsivo nativo nas imagens
    fig-format: "svg"       # (Opcional) Usa SVG para gráficos sem perda de qualidade ao escalar
    code-fold: false
    html-math-method: mathjax
    output-file: "notas.html"
    include-before-body: ../../assets/media/back-notes.html
  revealjs:
    transition: slide
    scrollable: false
    slide-number: false
    output-file: "slides.html"
    theme: [default, custom.scss]
    width: 1280
    height: 800
    margin: 0.02
    fig-width: 13           # Aumenta a largura nativa do SVG gerado para bater com 1280px
    fig-height: 5.2         # Altura proporcional para ocupar o slide
    fig-responsive: true    # Habilita CSS responsivo nativo nas imagens
    fig-format: "svg"       # (Opcional) Usa SVG para gráficos sem perda de qualidade ao escalar
    footer: "UNICAMP — Instituto de Computação"
    include-after-body: ../../assets/media/logos.html
    title-slide-attributes:
      data-background-image: "../../logos/UNICAMP.png, ../../logos/IC.png"
      data-background-size: "140px, 140px"
      data-background-position: "5% 8%, 95% 8%"
    chalkboard: 
      boardmarker-width: 3
      chalk-width: 3